### ISSUE TITLE
Safari Issues

### ISSUE THREAD

**Issue by Marc-Lorenz** [hcmlab/FaceMeshEditor#10]
On safari the initialization of the webgl fails

```
[Warning] W0604 12:32:29.206000 1880752 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default. (vision_wasm_internal.js, line 9)
[Log] I0604 12:32:29.231000 1880752 gl_context_webgl.cc:83] Couldn't create webGL 2 context. (vision_wasm_internal.js, line 9)
[Warning] W0604 12:32:29.233000 1880752 gl_context_webgl.cc:108] Creating a context with WebGL 2 failed: UNKNOWN: emscripten_webgl_create_context() returned error 0 (vision_wasm_internal.js, line 9)
=== Source Location Trace: ===
third_party/mediapipe/gpu/gl_context_webgl.cc:84
[Warning] W0604 12:32:29.233000 1880752 gl_context_webgl.cc:109] Fall back on WebGL 1. (vision_wasm_internal.js, line 9)
[Log] I0604 12:32:29.233000 1880752 gl_context_webgl.cc:83] Couldn't create webGL 1 context. (vision_wasm_internal.js, line 9)
```

**Comment by FHellmann** [comment]
Have you tried activating WebGL in your Safari Browser?

**Safari 5.1 to Safari 7**
To activate, you first need the developer menu, which you can turn on under Safari » Preferences » Advanced » Show “Developer” menu in the menu bar.
In the “Developer” menu that then appears, select the command “Enable WebGL”.

**From Safari 8**
1. Open the preferences under Safari » Preferences…
2. Select the “Security” section
3. Check the box next to “Allow WebGL”
4. If the box was already checked, click on “WebGL Settings”
5. Set the settings for the Koffermarkt website to “Allow” or “Always allow”

**Comment by Marc-Lorenz** [comment]
We are at Safari Version 17

I saw that. But WebGL is always enabled (no button to disable)
