### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by Marc-Lorenz** [hcmlab/FaceMeshEditor#8]
On mobile devices the website is unusable. 

# Option 1: View only (for small devices)

Opening up the website on a mobile enables a read only mode. The image is annotated by mediapipe or the remote and displayed. but there is no way to edit the points

# Option 2: Edit

For devices with bigger screens (tablets and alike) the UI might work. But still there needs some kind of support to hide the elements on the side and testing if the moving works properly on a touchscreen

**Comment by FHellmann** [comment]
Maybe some slide-in/-out navigation panel on both sides. Triggered by a button for each?

Something like this: [CSS Slide Out Panel](https://codepen.io/krisgrove/pen/prPdov)

**Comment by FHellmann** [comment]
This feature is unnecessary as it makes no sense to annotate on a mobile device. It's just not feasible.
